### ISSUE TITLE
(not really a bug) - is this the way to implements a full client-side CalDAV calenda/agenda ?

### ISSUE THREAD

**Issue by lebouquetin** [escoand/fullcalendar-plugins#16]
Hi @escoand . I'm the leader of tracim collaboration plateforme - https://github.com/tracim/tracim

Tracim integrate a full JS caldav client application based on caldavzap - https://inf-it.com/open-source/clients/caldavzap/

The calendar is ugly, not responsive at all and wwe are looking for a asubstitude software module. 

Our needs : an embeddable agenda application working with caldav protocol.

It looks like using fullcalendar + fullcalendar-plugins would be the solution.

Do you confirm this? We would be happy to upgrade tracim calendar/agenda part and to contribute if possible!

Let me know.

Thanks.

**Comment by escoand** [comment]
Hi,

I have used many different open source calendars and also created my own implementations (server rendered with PHP). But I was never happy with the rough edges left.

Now I use FullCalendar and I don't know of anything comparable.

Nextcloud has it integrated as a calendar tool too, so chances are pretty good that it will still be supported in the next few years.

So, yes, I am perfectly happy with it, except for the missing CalDav implementation. So I created this plugin for my own use. Perfectly sufficient for my needs.

I love the open source community and would be happy about any kind of reuse of my code and also collaboration.
